#include "cwmp/model.h"
#include "data_model.h"
#include "cwmp_module.h"
#include "InternetGatewayDevice/InternetGatewayDevice.c"
#include "Device/Device.c"

model_func_t ModelFunction[] =
{
    {"cpe_get_igd_di_manufacturer", cpe_get_igd_di_manufacturer},
    {"cpe_get_igd_di_manufactureroui", cpe_get_igd_di_manufactureroui},
    {"cpe_get_igd_di_productclass", cpe_get_igd_di_productclass},
    {"cpe_get_igd_di_ModelName", cpe_get_igd_di_ModelName},
    {"cpe_get_igd_di_ModelNumber", cpe_get_igd_di_ModelNumber},
    {"cpe_get_igd_di_Description", cpe_get_igd_di_Description},
    {"cpe_get_igd_di_serialnumber", cpe_get_igd_di_serialnumber},
    {"cpe_get_igd_di_specversion", cpe_get_igd_di_specversion},
    {"cpe_get_igd_di_hardwareversion", cpe_get_igd_di_hardwareversion},
    {"cpe_get_igd_di_softwareversion", cpe_get_igd_di_softwareversion},
	{"cpe_get_igd_di_configversion", cpe_get_igd_di_configversion},
	{"cpe_get_igd_di_workmode", cpe_get_igd_di_workmode},
    {"cpe_get_igd_di_provisioningcode", cpe_get_igd_di_provisioningcode},
    {"cpe_get_igd_di_AdditionalHardwareVersion", cpe_get_igd_di_AdditionalHardwareVersion},
    {"cpe_get_igd_di_AdditionalSoftwareVersion", cpe_get_igd_di_AdditionalSoftwareVersion},
    
	{"cpe_refresh_igd_wandevice", cpe_refresh_igd_wandevice},
    {"cpe_refresh_igd_wanconnectiondevice", cpe_refresh_igd_wanconnectiondevice},
    {"cpe_refresh_igd_wanipconnection", cpe_refresh_igd_wanipconnection},
    {"cpe_refresh_igd_WANPPPConnection",cpe_refresh_igd_WANPPPConnection},
	
    {"cpe_get_igd_wan_WANIPConnectionNumberOfEntries", cpe_get_igd_wan_WANIPConnectionNumberOfEntries},
    {"cpe_get_igd_wan_WANPPPConnectionNumberOfEntries", cpe_get_igd_wan_WANPPPConnectionNumberOfEntries},
    {"cpe_get_igd_wan_EthernetLinkStatus", cpe_get_igd_wan_EthernetLinkStatus},
    {"TRF_Get_DeviceSummary", TRF_Get_DeviceSummary},
	{"TRF_Get_LANDeviceNumberOfEntries", TRF_Get_LANDeviceNumberOfEntries},
    {"TRF_Get_WANDeviceNumberOfEntries", TRF_Get_WANDeviceNumberOfEntries},
	
	{"cpe_get_igd_https_Status", cpe_get_igd_https_Status},
	{"cpe_set_igd_https_Status", cpe_set_igd_https_Status},
	{"cpe_get_igd_https_Port", cpe_get_igd_https_Port},
	{"cpe_set_igd_https_Port", cpe_set_igd_https_Port},    

	{"cpe_get_igd_DownloadTransports", cpe_get_igd_DownloadTransports},
	{"cpe_get_igd_UploadTransports", cpe_get_igd_UploadTransports},

    {"cpe_get_igd_di_X_CMCC_ConfigVersion", cpe_get_igd_di_X_CMCC_ConfigVersion},
    {"cpe_get_igd_di_X_CMCC_ModuleVersion", cpe_get_igd_di_X_CMCC_ModuleVersion},
    {"cpe_get_igd_di_X_CMCC_ModuleType", cpe_get_igd_di_X_CMCC_ModuleType},
    {"cpe_get_igd_di_X_CMCC_IMEI", cpe_get_igd_di_X_CMCC_IMEI},
    {"cpe_get_igd_di_X_CMCC_IMSI", cpe_get_igd_di_X_CMCC_IMSI},
    {"cpe_get_igd_di_uptime", cpe_get_igd_di_uptime},
    {"cpe_set_attr_UpTime", cpe_set_attr_UpTime},

    {"cpe_get_igd_di_xcmccAlarm_alarmNumber", cpe_get_igd_di_xcmccAlarm_alarmNumber},
    {"cpe_get_igd_di_X_CMCC_WANDeviceNumberOfEntries", cpe_get_igd_di_X_CMCC_WANDeviceNumberOfEntries},
    {"cpe_get_igd_di_X_CMCC_NetRegStatus", cpe_get_igd_di_X_CMCC_NetRegStatus},
    {"cpe_get_igd_di_X_CMCC_GprsRegStatus", cpe_get_igd_di_X_CMCC_GprsRegStatus},
    {"cpe_get_igd_di_X_CMCC_EpsRegStatus", cpe_get_igd_di_X_CMCC_EpsRegStatus},
    {"cpe_get_igd_di_X_CMCC_CurrentNetwork", cpe_get_igd_di_X_CMCC_CurrentNetwork},
    {"cpe_get_igd_di_X_CMCC_CurrentNetmode", cpe_get_igd_di_X_CMCC_CurrentNetmode},
    {"cpe_get_igd_di_X_CMCC_NetworkPriority", cpe_get_igd_di_X_CMCC_NetworkPriority},
    {"cpe_get_igd_di_X_CMCC_SingalLevel", cpe_get_igd_di_X_CMCC_SingalLevel},
    {"cpe_get_igd_di_X_CMCC_Txpower", cpe_get_igd_di_X_CMCC_Txpower},
    {"cpe_get_igd_di_X_CMCC_FrequencyPoint", cpe_get_igd_di_X_CMCC_FrequencyPoint},
    {"cpe_get_igd_di_X_CMCC_Band", cpe_get_igd_di_X_CMCC_Band},
    {"cpe_get_igd_di_X_CMCC_BandWidth", cpe_get_igd_di_X_CMCC_BandWidth},
    {"cpe_get_igd_di_X_CMCC_EnodeBId", cpe_get_igd_di_X_CMCC_EnodeBId},
		
	{"cpe_get_igd_di_X_CMCC_LAC", cpe_get_igd_di_X_CMCC_LAC},
    {"cpe_get_igd_di_X_CMCC_CellId", cpe_get_igd_di_X_CMCC_CellId},
    {"cpe_get_igd_di_X_CMCC_GlobeCellId", cpe_get_igd_di_X_CMCC_GlobeCellId},
    {"cpe_get_igd_di_X_CMCC_PhysicsCellId", cpe_get_igd_di_X_CMCC_PhysicsCellId},
    {"cpe_get_igd_di_X_CMCC_ICCID", cpe_get_igd_di_X_CMCC_ICCID},
    {"cpe_get_igd_di_X_CMCC_APN", cpe_get_igd_di_X_CMCC_APN},
    {"cpe_get_igd_di_X_CMCC_IsFrequencyLock", cpe_get_igd_di_X_CMCC_IsFrequencyLock},
    {"cpe_get_igd_di_X_CMCC_FrequencyLocking", cpe_get_igd_di_X_CMCC_FrequencyLocking},
    {"cpe_get_igd_di_X_CMCC_FrequencyLockInfo", cpe_get_igd_di_X_CMCC_FrequencyLockInfo},
    {"cpe_get_igd_di_X_CMCC_IsCellLock", cpe_get_igd_di_X_CMCC_IsCellLock},
    {"cpe_get_igd_di_X_CMCC_CellLockType", cpe_get_igd_di_X_CMCC_CellLockType},
    
    {"cpe_get_igd_di_X_CMCC_CellLocking", cpe_get_igd_di_X_CMCC_CellLocking},
    {"cpe_set_igd_di_X_CMCC_CellLocking", cpe_set_igd_di_X_CMCC_CellLocking},
    
    {"cpe_get_igd_di_X_CMCC_CellLockInfo", cpe_get_igd_di_X_CMCC_CellLockInfo},
    {"cpe_get_igd_di_X_CMCC_LockPin", cpe_get_igd_di_X_CMCC_LockPin},
    {"cpe_get_igd_di_X_CMCC_LockPinType", cpe_get_igd_di_X_CMCC_LockPinType},
    {"cpe_get_igd_di_X_CMCC_FirstPin", cpe_get_igd_di_X_CMCC_FirstPin},
    {"cpe_get_igd_di_X_CMCC_FixedPin", cpe_get_igd_di_X_CMCC_FixedPin},
    {"cpe_get_igd_di_X_CMCC_EncryptCard", cpe_get_igd_di_X_CMCC_EncryptCard},
    {"cpe_get_igd_di_X_CMCC_EncryptCardKey", cpe_get_igd_di_X_CMCC_EncryptCardKey},

	
    {"cpe_get_igd_HostNumberOfEntries", cpe_get_igd_HostNumberOfEntries},
    {"cpe_refresh_igd_Host", cpe_refresh_igd_Host},
    {"cpe_get_igd_ActiveOfHost", cpe_get_igd_ActiveOfHost},
    {"cpe_get_igd_HostName", cpe_get_igd_HostName},
    {"cpe_get_igd_InterfaceType", cpe_get_igd_InterfaceType},
    {"cpe_get_igd_Layer2Interface", cpe_get_igd_Layer2Interface},
    {"cpe_get_IPAddress", cpe_get_IPAddress},
    {"cpe_get_AddressSourceOfHost", cpe_get_AddressSourceOfHost},
    {"cpe_get_LeaseTimeRemainingOfHost", cpe_get_LeaseTimeRemainingOfHost},
    {"cpe_get_igd_MACAddressOfHost", cpe_get_igd_MACAddressOfHost},
	{"cpe_get_igd_di_X_CMCC_PLMN", cpe_get_igd_di_X_CMCC_PLMN},
	{"cpe_get_igd_di_X_CMCC_SignalQuality", cpe_get_igd_di_X_CMCC_SignalQuality},
	{"cpe_get_igd_di_X_CMCC_RSSI", cpe_get_igd_di_X_CMCC_RSSI},
    {"cpe_get_igd_di_X_CMCC_RSRP", cpe_get_igd_di_X_CMCC_RSRP},
    {"cpe_get_igd_di_X_CMCC_RSRQ", cpe_get_igd_di_X_CMCC_RSRQ},
    {"cpe_get_igd_di_X_CMCC_SINR", cpe_get_igd_di_X_CMCC_SINR},

    {"cpe_get_igd_di_X_CMCC_CQI", cpe_get_igd_di_X_CMCC_CQI},
    {"cpe_get_igd_di_X_CMCC_MCS", cpe_get_igd_di_X_CMCC_MCS},    
    
    {"cpe_get_igd_di_X_CMCC_SupportedBands", cpe_get_igd_di_X_CMCC_SupportedBands},
    {"cpe_set_igd_di_X_CMCC_SupportedBands", cpe_set_igd_di_X_CMCC_SupportedBands},
    
    {"cpe_get_igd_di_X_CMCC_UpstreamTotalByte", cpe_get_igd_di_X_CMCC_UpstreamTotalByte},
    {"cpe_get_igd_di_X_CMCC_DownstreamTotalByte", cpe_get_igd_di_X_CMCC_DownstreamTotalByte},
    {"cpe_get_igd_di_X_CMCC_StartTime", cpe_get_igd_di_X_CMCC_StartTime},
    {"cpe_get_igd_di_X_CMCC_LoadAverage", cpe_get_igd_di_X_CMCC_LoadAverage},
    {"cpe_get_igd_di_X_CMCC_DeviceMemory", cpe_get_igd_di_X_CMCC_DeviceMemory},
    {"cpe_get_igd_di_X_CMCC_MTU", cpe_get_igd_di_X_CMCC_MTU},

	{"cpe_get_igd_di_X_CMCC_Antenna1", cpe_get_igd_di_X_CMCC_Antenna1},
    {"cpe_get_igd_di_X_CMCC_Antenna2", cpe_get_igd_di_X_CMCC_Antenna2},
    {"cpe_get_igd_di_X_SearchNetMode", cpe_get_igd_di_X_SearchNetMode},
    {"cpe_set_igd_di_X_SearchNetMode", cpe_set_igd_di_X_SearchNetMode},
    {"cpe_get_igd_di_X_RoamingStatus", cpe_get_igd_di_X_RoamingStatus},
    {"cpe_set_igd_di_X_RoamingStatus", cpe_set_igd_di_X_RoamingStatus},
		
		
		
	{"cpe_get_igd_ms_url", cpe_get_igd_ms_url},
	{"cpe_set_igd_ms_url", cpe_set_igd_ms_url},
	{"cpe_get_igd_ms_username", cpe_get_igd_ms_username},
	{"cpe_set_igd_ms_username", cpe_set_igd_ms_username},
	{"cpe_get_igd_ms_password", cpe_get_igd_ms_password},
	{"cpe_set_igd_ms_password", cpe_set_igd_ms_password},
	{"cpe_get_igd_ms_connectionrequesturl", cpe_get_igd_ms_connectionrequesturl},
	{"cpe_get_igd_ms_connectionrequestusername", cpe_get_igd_ms_connectionrequestusername},
	{"cpe_set_igd_ms_connectionrequestusername", cpe_set_igd_ms_connectionrequestusername},
	{"cpe_get_igd_ms_connectionrequestpassword", cpe_get_igd_ms_connectionrequestpassword},
	{"cpe_set_igd_ms_connectionrequestpassword", cpe_set_igd_ms_connectionrequestpassword},
	{"cpe_get_igd_ms_UpgradesManaged", cpe_get_igd_ms_UpgradesManaged},
    {"cpe_get_igd_ms_period_en", cpe_get_igd_ms_period_en},
    {"cpe_set_igd_ms_period_en", cpe_set_igd_ms_period_en},
	{"cpe_get_igd_ms_period_intval", cpe_get_igd_ms_period_intval},
	{"cpe_set_igd_ms_period_intval", cpe_set_igd_ms_period_intval},
	{"cpe_get_igd_ms_aliasbasedaddressing", cpe_get_igd_ms_aliasbasedaddressing},

	{"cpe_get_igd_Time_Enable", cpe_get_igd_Time_Enable},
	{"cpe_get_igd_Time_Status", cpe_get_igd_Time_Status},
	{"cpe_get_igd_Time_NTPServer1", cpe_get_igd_Time_NTPServer1},
	{"cpe_set_igd_Time_NTPServer1", cpe_set_igd_Time_NTPServer1},
	{"cpe_get_igd_Time_NTPServer2", cpe_get_igd_Time_NTPServer2},
	{"cpe_set_igd_Time_NTPServer2", cpe_set_igd_Time_NTPServer2},
	{"cpe_get_igd_Time_NTPServer3", cpe_get_igd_Time_NTPServer3},
	{"cpe_set_igd_Time_NTPServer3", cpe_set_igd_Time_NTPServer3},
	{"cpe_get_igd_Time_NTPServer4", cpe_get_igd_Time_NTPServer4},
	{"cpe_set_igd_Time_NTPServer4", cpe_set_igd_Time_NTPServer4},
	{"cpe_get_igd_Time_CurrentLocalTime", cpe_get_igd_Time_CurrentLocalTime},
	{"cpe_get_igd_Time_LocalTimeZone", cpe_get_igd_Time_LocalTimeZone},
	{"cpe_get_igd_Time_LocalTimeZoneName", cpe_get_igd_Time_LocalTimeZoneName},

	{"cpe_get_igd_LANEthernetInterfaceNumberOfEntries", cpe_get_igd_LANEthernetInterfaceNumberOfEntries},
	{"cpe_get_igd_LANWLANConfigurationNumberOfEntries", cpe_get_igd_LANWLANConfigurationNumberOfEntries},
    {"cpe_get_igd_MACAddress",cpe_get_igd_MACAddress},
	{"cpe_get_igd_DHCPServerConfigurable", cpe_get_igd_DHCPServerConfigurable},
	{"cpe_set_igd_DHCPServerConfigurable", cpe_set_igd_DHCPServerConfigurable},
	{"cpe_get_igd_DHCPServerEnable", cpe_get_igd_DHCPServerEnable},
	{"cpe_set_igd_DHCPServerEnable", cpe_set_igd_DHCPServerEnable},
	{"cpe_get_igd_DHCPRelay", cpe_get_igd_DHCPRelay},
	{"cpe_get_igd_MinAddress", cpe_get_igd_MinAddress},
	{"cpe_set_igd_MinAddress", cpe_set_igd_MinAddress},
	{"cpe_get_igd_MaxAddress", cpe_get_igd_MaxAddress},
	{"cpe_set_igd_MaxAddress", cpe_set_igd_MaxAddress},
	{"cpe_get_igd_ReservedAddresses", cpe_get_igd_ReservedAddresses},
	{"cpe_get_igd_SubnetMask", cpe_get_igd_SubnetMask},
	{"cpe_set_igd_SubnetMask", cpe_set_igd_SubnetMask},
	{"cpe_get_igd_DNSServers", cpe_get_igd_DNSServers},
	{"cpe_set_igd_DNSServers", cpe_set_igd_DNSServers},
	{"cpe_get_igd_DomainName", cpe_get_igd_DomainName},
	{"cpe_set_igd_DomainName", cpe_set_igd_DomainName},
	{"cpe_get_igd_IPRouters", cpe_get_igd_IPRouters},
	//{"cpe_set_igd_IPRouters", cpe_set_igd_IPRouters},
	{"cpe_get_igd_DHCPLeaseTime", cpe_get_igd_DHCPLeaseTime},
	{"cpe_set_igd_DHCPLeaseTime", cpe_set_igd_DHCPLeaseTime},
	{"cpe_get_igd_IPInterfaceNumberOfEntries", cpe_get_igd_IPInterfaceNumberOfEntries},
	{"cpe_get_igd_DHCPStaticAddressNumberOfEntries", cpe_get_igd_DHCPStaticAddressNumberOfEntries},
	{"cpe_get_igd_EnableOfIPInterface", cpe_get_igd_EnableOfIPInterface},
	{"cpe_set_igd_EnableOfIPInterface", cpe_set_igd_EnableOfIPInterface},
	{"cpe_get_igd_IPInterfaceIPAddress", cpe_get_igd_IPInterfaceIPAddress},
	{"cpe_set_igd_IPInterfaceIPAddress", cpe_set_igd_IPInterfaceIPAddress},
	{"cpe_get_igd_IPInterfaceSubnetMask", cpe_get_igd_IPInterfaceSubnetMask},
	{"cpe_set_igd_IPInterfaceSubnetMask", cpe_set_igd_IPInterfaceSubnetMask},
	{"cpe_get_igd_IPInterfaceAddressingType", cpe_get_igd_IPInterfaceAddressingType},
	{"cpe_get_igd_DHCPStaticAddressEnable", cpe_get_igd_DHCPStaticAddressEnable},
	{"cpe_set_igd_DHCPStaticAddressEnable", cpe_set_igd_DHCPStaticAddressEnable},
	{"cpe_get_igd_DHCPStaticAddressMac", cpe_get_igd_DHCPStaticAddressMac},
	{"cpe_set_igd_DHCPStaticAddressMac", cpe_set_igd_DHCPStaticAddressMac},
	{"cpe_get_igd_DHCPStaticAddressIp", cpe_get_igd_DHCPStaticAddressIp},
	{"cpe_set_igd_DHCPStaticAddressIp", cpe_set_igd_DHCPStaticAddressIp},
	{"cpe_refresh_igd_DHCPStaticAddress", cpe_refresh_igd_DHCPStaticAddress},
	{"cpe_add_igd_DHCPStaticAddress", cpe_add_igd_DHCPStaticAddress},
	{"cpe_del_igd_DHCPStaticAddress", cpe_del_igd_DHCPStaticAddress},


	{"cpe_get_igd_EnableOfEth", cpe_get_igd_EnableOfEth},
	{"cpe_set_igd_EnableOfEth", cpe_set_igd_EnableOfEth},
	{"cpe_get_igd_StatusOfEth", cpe_get_igd_StatusOfEth},
	{"cpe_get_igd_NameofLANEth", cpe_get_igd_NameofLANEth},
	{"cpe_get_igd_MACAddressOfEth", cpe_get_igd_MACAddressOfEth},
	{"cpe_get_igd_MaxBitRateOfEth", cpe_get_igd_MaxBitRateOfEth},
	{"cpe_get_igd_DuplexModeOfEth", cpe_get_igd_DuplexModeOfEth},
	{"cpe_get_igd_BytesSentOfEth", cpe_get_igd_BytesSentOfEth},
	{"cpe_get_igd_BytesReceivedOfEth", cpe_get_igd_BytesReceivedOfEth},
	{"cpe_get_igd_PacketsSentOfEth", cpe_get_igd_PacketsSentOfEth},
	{"cpe_get_igd_PacketsReceivedOfEth", cpe_get_igd_PacketsReceivedOfEth},
	{"cpe_get_igd_ErrorsSentOfEth", cpe_get_igd_ErrorsSentOfEth},
	{"cpe_get_igd_ErrorsReceivedOfEth", cpe_get_igd_ErrorsReceivedOfEth},


	
    {"cpe_get_igd_wan_ip_WANIPConnectionEnable", cpe_get_igd_wan_ip_WANIPConnectionEnable},
    {"cpe_get_igd_wan_ip_AddressingType", cpe_get_igd_wan_ip_AddressingType},
    {"cpe_get_igd_wan_ip_ExternalIPAddress", cpe_get_igd_wan_ip_ExternalIPAddress},
    {"cpe_get_igd_wan_ip_SubnetMask", cpe_get_igd_wan_ip_SubnetMask},
    {"cpe_get_igd_wan_ip_DefaultGateway", cpe_get_igd_wan_ip_DefaultGateway},
    {"cpe_get_igd_wan_ip_DNSServers", cpe_get_igd_wan_ip_DNSServers},
    {"cpe_get_igd_wan_ip_MACAddress", cpe_get_igd_wan_ip_MACAddress},
    {"cpe_get_igd_wan_ip_EthernetBytesSent", cpe_get_igd_wan_ip_EthernetBytesSent},
    {"cpe_get_igd_wan_ip_EthernetBytesReceived", cpe_get_igd_wan_ip_EthernetBytesReceived},
    {"cpe_get_igd_wan_ip_EthernetPacketsSent", cpe_get_igd_wan_ip_EthernetPacketsSent},
    {"cpe_get_igd_wan_ip_EthernetPacketsReceived", cpe_get_igd_wan_ip_EthernetPacketsReceived},
    {"cpe_get_igd_wan_ip_EthernetErrorsSent", cpe_get_igd_wan_ip_EthernetErrorsSent},
    {"cpe_get_igd_wan_ip_EthernetErrorsReceived", cpe_get_igd_wan_ip_EthernetErrorsReceived},
    {"cpe_get_igd_wan_ip_EthernetDiscardPacketsSent", cpe_get_igd_wan_ip_EthernetDiscardPacketsSent},
    {"cpe_get_igd_wan_ip_EthernetDiscardPacketsReceived", cpe_get_igd_wan_ip_EthernetDiscardPacketsReceived},
    {"cpe_get_igd_wan_ip_ConnectionStatus", cpe_get_igd_wan_ip_ConnectionStatus},
    {"cpe_get_igd_wan_ip_ConnectionTrigger", cpe_get_igd_wan_ip_ConnectionTrigger},
    {"cpe_get_igd_wan_ip_ConnectionType", cpe_get_igd_wan_ip_ConnectionType},
    {"cpe_get_igd_wan_ip_DNSEnabled", cpe_get_igd_wan_ip_DNSEnabled},
    {"cpe_get_igd_wan_ip_DNSOverrideAllowed", cpe_get_igd_wan_ip_DNSOverrideAllowed},
    {"cpe_get_igd_wan_ip_LastConnectionError", cpe_get_igd_wan_ip_LastConnectionError},
    {"cpe_get_igd_wan_ip_MACAddressOverride", cpe_get_igd_wan_ip_MACAddressOverride},
    {"cpe_get_igd_wan_ip_MaxMTUSize", cpe_get_igd_wan_ip_MaxMTUSize},
    {"cpe_get_igd_wan_ip_Name", cpe_get_igd_wan_ip_Name},
    {"cpe_get_igd_wan_ip_PossibleConnectionTypes", cpe_get_igd_wan_ip_PossibleConnectionTypes},
    {"cpe_get_igd_wan_ip_RSIPAvailable", cpe_get_igd_wan_ip_RSIPAvailable},
    {"cpe_get_igd_wan_ip_RouteProtocolRx", cpe_get_igd_wan_ip_RouteProtocolRx},
    {"cpe_get_igd_wan_ip_Uptime", cpe_get_igd_wan_ip_Uptime},
    {"cpe_get_igd_wan_ip_PortMappingNumberOfEntries", cpe_get_igd_wan_ip_PortMappingNumberOfEntries},
    {"cpe_add_igd_wan_ip_PortMapping", cpe_add_igd_wan_ip_PortMapping},
    {"cpe_del_igd_wan_ip_PortMapping", cpe_del_igd_wan_ip_PortMapping},
    {"cpe_refresh_igd_wan_ip_PortMapping", cpe_refresh_igd_wan_ip_PortMapping},
    {"cpe_get_igd_wan_ip_PortMapping_Enabled", cpe_get_igd_wan_ip_PortMapping_Enabled},
    {"cpe_set_igd_wan_ip_PortMapping_Enabled", cpe_set_igd_wan_ip_PortMapping_Enabled},
    {"cpe_get_igd_wan_ip_PortMapping_ExternalPort", cpe_get_igd_wan_ip_PortMapping_ExternalPort},
    {"cpe_set_igd_wan_ip_PortMapping_ExternalPort", cpe_set_igd_wan_ip_PortMapping_ExternalPort},
    {"cpe_get_igd_wan_ip_PortMapping_InternalPort", cpe_get_igd_wan_ip_PortMapping_InternalPort},
    {"cpe_set_igd_wan_ip_PortMapping_InternalPort", cpe_set_igd_wan_ip_PortMapping_InternalPort},
    {"cpe_get_igd_wan_ip_PortMapping_InternalClient", cpe_get_igd_wan_ip_PortMapping_InternalClient},
    {"cpe_set_igd_wan_ip_PortMapping_InternalClient", cpe_set_igd_wan_ip_PortMapping_InternalClient},

    {"cpe_get_igd_wan_ppp_WANPPPConnectionEnable", cpe_get_igd_wan_ppp_WANPPPConnectionEnable},
    {"cpe_get_igd_wan_ppp_ExternalIPAddress", cpe_get_igd_wan_ppp_ExternalIPAddress},
    {"cpe_get_igd_wan_ppp_DefaultGateway", cpe_get_igd_wan_ppp_DefaultGateway},
    {"cpe_get_igd_wan_ppp_DNSServers", cpe_get_igd_wan_ppp_DNSServers},
    {"cpe_get_igd_wan_ppp_MACAddress", cpe_get_igd_wan_ppp_MACAddress},
    {"cpe_get_igd_wan_ppp_ConnectionStatus", cpe_get_igd_wan_ppp_ConnectionStatus},
    {"cpe_get_igd_wan_ppp_ConnectionTrigger", cpe_get_igd_wan_ppp_ConnectionTrigger},
    {"cpe_get_igd_wan_ppp_ConnectionType", cpe_get_igd_wan_ppp_ConnectionType},
    {"cpe_get_igd_wan_ppp_DNSEnabled", cpe_get_igd_wan_ppp_DNSEnabled},
    {"cpe_get_igd_wan_ppp_DNSOverrideAllowed", cpe_get_igd_wan_ppp_DNSOverrideAllowed},
    {"cpe_get_igd_wan_ppp_LastConnectionError", cpe_get_igd_wan_ppp_LastConnectionError},
    {"cpe_get_igd_wan_ppp_MACAddressOverride", cpe_get_igd_wan_ppp_MACAddressOverride},
    {"cpe_get_igd_wan_ppp_MaxMTUSize", cpe_get_igd_wan_ppp_MaxMTUSize},
    {"cpe_get_igd_wan_ppp_Name", cpe_get_igd_wan_ppp_Name},
    {"cpe_get_igd_wan_ppp_PossibleConnectionTypes", cpe_get_igd_wan_ppp_PossibleConnectionTypes},
    {"cpe_get_igd_wan_ppp_RouteProtocolRx", cpe_get_igd_wan_ppp_RouteProtocolRx},
    {"cpe_get_igd_wan_ppp_Uptime", cpe_get_igd_wan_ppp_Uptime},
    {"cpe_get_igd_wan_ppp_Username", cpe_get_igd_wan_ppp_Username},
    {"cpe_set_igd_wan_ppp_Username", cpe_set_igd_wan_ppp_Username},
    {"cpe_get_igd_wan_ppp_Password", cpe_get_igd_wan_ppp_Password},
    {"cpe_set_igd_wan_ppp_Password", cpe_set_igd_wan_ppp_Password},
    {"cpe_get_igd_wan_ppp_EthernetBytesSent",cpe_get_igd_wan_ppp_EthernetBytesSent},
    {"cpe_get_igd_wan_ppp_EthernetBytesReceived",cpe_get_igd_wan_ppp_EthernetBytesReceived},

    {"cpe_get_idg_EnableofWANCommonInterfaceConfig", cpe_get_idg_EnableofWANCommonInterfaceConfig},
    {"cpe_set_idg_EnableofWANCommonInterfaceConfig", cpe_set_idg_EnableofWANCommonInterfaceConfig},
    {"cpe_get_idg_Layer1UpstreamMaxBitRate", cpe_get_idg_Layer1UpstreamMaxBitRate},
    {"cpe_get_idg_Layer1DownstreamMaxBitRate", cpe_get_idg_Layer1DownstreamMaxBitRate},
    {"cpe_get_idg_PhysicalLinkStatus", cpe_get_idg_PhysicalLinkStatus},
    {"cpe_get_idg_PhysicalLinkStatus", cpe_get_idg_PhysicalLinkStatus},
    {"cpe_get_idg_TotalBytesSentofWANCommonInterfaceConfig", cpe_get_idg_TotalBytesSentofWANCommonInterfaceConfig},
    {"cpe_get_idg_TotalBytesReceivedofWANCommonInterfaceConfig", cpe_get_idg_TotalBytesReceivedofWANCommonInterfaceConfig},
    {"cpe_get_idg_MaximumActiveConnections", cpe_get_idg_MaximumActiveConnections},
    {"cpe_get_idg_NumberOfActiveConnections", cpe_get_idg_NumberOfActiveConnections},
    {"cpe_get_idg_StatusofWANEthernetInterfaceConfig", cpe_get_idg_StatusofWANEthernetInterfaceConfig},
    {"cpe_get_idg_MACAddressofWANEthernetInterfaceConfig", cpe_get_idg_MACAddressofWANEthernetInterfaceConfig},
    {"cpe_get_idg_MaxBitRateofWANEthernetInterfaceConfig", cpe_get_idg_MaxBitRateofWANEthernetInterfaceConfig},
    {"cpe_get_idg_DuplexModeofWANEthernetInterfaceConfig", cpe_get_idg_DuplexModeofWANEthernetInterfaceConfig},
    {"cpe_get_idg_BytesSentofWANEthernetInterfaceConfig", cpe_get_idg_BytesSentofWANEthernetInterfaceConfig},
    {"cpe_get_idg_BytesReceivedofWANEthernetInterfaceConfig", cpe_get_idg_BytesReceivedofWANEthernetInterfaceConfig},
    {"cpe_get_idg_PacketsSentofWANEthernetInterfaceConfig", cpe_get_idg_PacketsSentofWANEthernetInterfaceConfig},
    {"cpe_get_idg_PacketsReceivedofWANEthernetInterfaceConfig", cpe_get_idg_PacketsReceivedofWANEthernetInterfaceConfig},
		

    {"cpe_get_igd_WANPPPConnection_Enable", cpe_get_igd_WANPPPConnection_Enable},
    {"cpe_set_igd_WANPPPConnection_Enable", cpe_set_igd_WANPPPConnection_Enable},
    
    {"cpe_get_igd_WANPPPConnection_Name", cpe_get_igd_WANPPPConnection_Name},
    {"cpe_set_igd_WANPPPConnection_Name", cpe_set_igd_WANPPPConnection_Name},

    {"cpe_get_igd_WANPPPConnection_Uptime", cpe_get_igd_WANPPPConnection_Uptime},
    {"cpe_get_igd_WANPPPConnection_LastConnectionError", cpe_get_igd_WANPPPConnection_LastConnectionError},
	{"cpe_get_igd_WANPPPConnection_Username", cpe_get_igd_WANPPPConnection_Username},
	{"cpe_get_igd_WANPPPConnection_Password", cpe_get_igd_WANPPPConnection_Password},
	{"cpe_get_igd_WANPPPConnection_ExternalIPAddress", cpe_get_igd_WANPPPConnection_ExternalIPAddress},

    {"cpe_get_igd_WANPPPConnection_DNSEnabled", cpe_get_igd_WANPPPConnection_DNSEnabled},
    {"cpe_set_igd_WANPPPConnection_DNSEnabled", cpe_set_igd_WANPPPConnection_DNSEnabled},

    {"cpe_get_igd_WANPPPConnection_DNSServers", cpe_get_igd_WANPPPConnection_DNSServers},
    {"cpe_set_igd_WANPPPConnection_DNSServers", cpe_set_igd_WANPPPConnection_DNSServers},

    {"cpe_get_igd_WANPPPConnection_MACAddress", cpe_get_igd_WANPPPConnection_MACAddress},

    {"cpe_get_igd_WANPPPConnection_X_CMCC_TunnelDial", cpe_get_igd_WANPPPConnection_X_CMCC_TunnelDial},
    {"cpe_set_igd_WANPPPConnection_X_CMCC_TunnelDial", cpe_set_igd_WANPPPConnection_X_CMCC_TunnelDial},

    {"cpe_get_igd_WANPPPConnection_X_CMCC_LNS", cpe_get_igd_WANPPPConnection_X_CMCC_LNS},
    {"cpe_set_igd_WANPPPConnection_X_CMCC_LNS", cpe_set_igd_WANPPPConnection_X_CMCC_LNS},

    {"cpe_get_igd_WANPPPConnection_X_CMCC_LnsIp", cpe_get_igd_WANPPPConnection_X_CMCC_LnsIp},
    {"cpe_set_igd_WANPPPConnection_X_CMCC_LnsIp", cpe_set_igd_WANPPPConnection_X_CMCC_LnsIp},

    {"cpe_get_igd_WANPPPConnection_X_CMCC_LnsName", cpe_get_igd_WANPPPConnection_X_CMCC_LnsName},
    {"cpe_set_igd_WANPPPConnection_X_CMCC_LnsName", cpe_set_igd_WANPPPConnection_X_CMCC_LnsName},

    {"cpe_get_igd_WANPPPConnection_X_CMCC_LnsPassword", cpe_get_igd_WANPPPConnection_X_CMCC_LnsPassword},
    {"cpe_set_igd_WANPPPConnection_X_CMCC_LnsPassword", cpe_set_igd_WANPPPConnection_X_CMCC_LnsPassword},

    {"cpe_get_igd_WANPPPConnection_X_CMCC_L2TPMode", cpe_get_igd_WANPPPConnection_X_CMCC_L2TPMode},
    {"cpe_set_igd_WANPPPConnection_X_CMCC_L2TPMode", cpe_set_igd_WANPPPConnection_X_CMCC_L2TPMode},

	{"cpe_get_igd_WANPPPConnection_X_CMCC_UpstreamTotalByte", cpe_get_igd_WANPPPConnection_X_CMCC_UpstreamTotalByte},

	{"cpe_get_igd_WANPPPConnection_X_CMCC_DownstreamTotalByte", cpe_get_igd_WANPPPConnection_X_CMCC_DownstreamTotalByte},

	{"cpe_add_igd_WANPPPConnection", cpe_add_igd_WANPPPConnection},
	{"cpe_del_igd_WANPPPConnection", cpe_del_igd_WANPPPConnection},
	

	{"cpe_get_igd_di_X_CMCC_TeleComAccount_Enable", cpe_get_igd_di_X_CMCC_TeleComAccount_Enable},
    {"cpe_set_igd_di_X_CMCC_TeleComAccount_Enable", cpe_set_igd_di_X_CMCC_TeleComAccount_Enable},

    {"cpe_get_igd_di_X_CMCC_TeleComAccount_Username", cpe_get_igd_di_X_CMCC_TeleComAccount_Username},
    {"cpe_set_igd_di_X_CMCC_TeleComAccount_Username", cpe_set_igd_di_X_CMCC_TeleComAccount_Username},

    {"cpe_get_igd_di_X_CMCC_TeleComAccount_Password", cpe_get_igd_di_X_CMCC_TeleComAccount_Password},
    {"cpe_set_igd_di_X_CMCC_TeleComAccount_Password", cpe_set_igd_di_X_CMCC_TeleComAccount_Password},

	{"cpe_get_igd_di_X_CMCC_UserInfo_Password", cpe_get_igd_di_X_CMCC_UserInfo_Password},
    {"cpe_set_igd_di_X_CMCC_UserInfo_Password", cpe_set_igd_di_X_CMCC_UserInfo_Password},

  	{"cpe_get_igd_di_X_CMCC_UserInfo_Status", cpe_get_igd_di_X_CMCC_UserInfo_Status},
    {"cpe_set_igd_di_X_CMCC_UserInfo_Status", cpe_set_igd_di_X_CMCC_UserInfo_Status},

	{"cpe_get_igd_di_X_CMCC_UserInfo_Limit", cpe_get_igd_di_X_CMCC_UserInfo_Limit},
    {"cpe_set_igd_di_X_CMCC_UserInfo_Limit", cpe_set_igd_di_X_CMCC_UserInfo_Limit},

    {"cpe_get_igd_di_X_CMCC_UserInfo_Times", cpe_get_igd_di_X_CMCC_UserInfo_Times},
    {"cpe_set_igd_di_X_CMCC_UserInfo_Times", cpe_set_igd_di_X_CMCC_UserInfo_Times},

    {"cpe_get_igd_di_X_CMCC_UserInfo_Result", cpe_get_igd_di_X_CMCC_UserInfo_Result},
    {"cpe_set_igd_di_X_CMCC_UserInfo_Result", cpe_set_igd_di_X_CMCC_UserInfo_Result},

    {"cpe_get_igd_di_X_CMCC_UserInfo_ServiceNum", cpe_get_igd_di_X_CMCC_UserInfo_ServiceNum},
    {"cpe_set_igd_di_X_CMCC_UserInfo_ServiceNum", cpe_set_igd_di_X_CMCC_UserInfo_ServiceNum},

    {"cpe_get_igd_di_X_CMCC_UserInfo_ServiceName", cpe_get_igd_di_X_CMCC_UserInfo_ServiceName},
    {"cpe_set_igd_di_X_CMCC_UserInfo_ServiceName", cpe_set_igd_di_X_CMCC_UserInfo_ServiceName},

	
	{"cpe_get_igd_ping_DiagnosticsState", cpe_get_igd_ping_DiagnosticsState},
	{"cpe_set_igd_ping_DiagnosticsState", cpe_set_igd_ping_DiagnosticsState},

	{"cpe_get_igd_ping_Interface", cpe_get_igd_ping_Interface},
	{"cpe_set_igd_ping_Interface", cpe_set_igd_ping_Interface},

	{"cpe_get_igd_ping_Host", cpe_get_igd_ping_Host},
	{"cpe_set_igd_ping_Host", cpe_set_igd_ping_Host},

	{"cpe_get_igd_ping_NumberOfRepetitions", cpe_get_igd_ping_NumberOfRepetitions},
	{"cpe_set_igd_ping_NumberOfRepetitions", cpe_set_igd_ping_NumberOfRepetitions},
	
	{"cpe_get_igd_ping_Timeout", cpe_get_igd_ping_Timeout},
	{"cpe_set_igd_ping_Timeout", cpe_set_igd_ping_Timeout},
	
	{"cpe_get_igd_ping_DataBlockSize", cpe_get_igd_ping_DataBlockSize},
	{"cpe_set_igd_ping_DataBlockSize", cpe_set_igd_ping_DataBlockSize},
	
	{"cpe_get_igd_ping_DSCP", cpe_get_igd_ping_DSCP},
	{"cpe_set_igd_ping_DSCP", cpe_set_igd_ping_DSCP},
		
	{"cpe_get_igd_ping_SuccessCount", cpe_get_igd_ping_SuccessCount},
	{"cpe_get_igd_ping_FailureCount", cpe_get_igd_ping_FailureCount},
	{"cpe_get_igd_ping_AverageResponseTime", cpe_get_igd_ping_AverageResponseTime},
	{"cpe_get_igd_ping_MinimumResponseTime", cpe_get_igd_ping_MinimumResponseTime},
	{"cpe_get_igd_ping_MaximumResponseTime", cpe_get_igd_ping_MaximumResponseTime},
	
	{"cpe_get_igd_tr_DiagnosticsState", cpe_get_igd_tr_DiagnosticsState},
	{"cpe_set_igd_tr_DiagnosticsState", cpe_set_igd_tr_DiagnosticsState},
	
	{"cpe_get_igd_tr_Interface", cpe_get_igd_tr_Interface},
	{"cpe_set_igd_tr_Interface", cpe_set_igd_tr_Interface},
	
	{"cpe_get_igd_tr_Host", cpe_get_igd_tr_Host},
	{"cpe_set_igd_tr_Host", cpe_set_igd_tr_Host},
	
	{"cpe_get_igd_tr_NumberOfTries", cpe_get_igd_tr_NumberOfTries},
	{"cpe_set_igd_tr_NumberOfTries", cpe_set_igd_tr_NumberOfTries},
	
	{"cpe_get_igd_tr_Timeout", cpe_get_igd_tr_Timeout},
	{"cpe_set_igd_tr_Timeout", cpe_set_igd_tr_Timeout},
	
	{"cpe_get_igd_tr_DataBlockSize", cpe_get_igd_tr_DataBlockSize},
	{"cpe_set_igd_tr_DataBlockSize", cpe_set_igd_tr_DataBlockSize},
	
	{"cpe_get_igd_tr_DSCP", cpe_get_igd_tr_DSCP},
	{"cpe_set_igd_tr_DSCP", cpe_set_igd_tr_DSCP},
	
	{"cpe_get_igd_tr_MaxHopCount", cpe_get_igd_tr_MaxHopCount},
	{"cpe_set_igd_tr_MaxHopCount", cpe_set_igd_tr_MaxHopCount},
	
	{"cpe_get_igd_tr_ResponseTime", cpe_get_igd_tr_ResponseTime},
	{"cpe_get_igd_tr_HopsNumberOfEntries", cpe_get_igd_tr_HopsNumberOfEntries},

	
	{"cpe_add_igd_tr_RouteHops", cpe_add_igd_tr_RouteHops},
	{"cpe_del_igd_tr_RouteHops", cpe_del_igd_tr_RouteHops},
	{"cpe_refresh_igd_TraceRouteDiagnostics_RouteHops", cpe_refresh_igd_tr_RouteHops},
	
	{"cpe_get_igd_tr_HopHost", cpe_get_igd_tr_HopHost},
	{"cpe_get_igd_tr_HopHostAddress", cpe_get_igd_tr_HopHostAddress},
	{"cpe_get_igd_tr_HopErrorCode", cpe_get_igd_tr_HopErrorCode},
	{"cpe_get_igd_tr_HopRTTimes", cpe_get_igd_tr_HopRTTimes},

	{"cpe_get_igd_Download_DiagnosticsState", cpe_get_igd_Download_DiagnosticsState},
    {"cpe_set_igd_Download_DiagnosticsState", cpe_set_igd_Download_DiagnosticsState},
    {"cpe_get_igd_Download_Interface", cpe_get_igd_Download_Interface},
    {"cpe_set_igd_Download_Interface", cpe_set_igd_Download_Interface},
    {"cpe_get_igd_Download_URL", cpe_get_igd_Download_URL},
    {"cpe_set_igd_Download_URL", cpe_set_igd_Download_URL},
    {"cpe_get_igd_Download_DSCP", cpe_get_igd_Download_DSCP},
    {"cpe_set_igd_Download_DSCP", cpe_set_igd_Download_DSCP},
    {"cpe_get_igd_Download_Priority", cpe_get_igd_Download_Priority},
    {"cpe_set_igd_Download_Priority", cpe_set_igd_Download_Priority},
    {"cpe_get_igd_Download_ROMTime", cpe_get_igd_Download_ROMTime},
    {"cpe_get_igd_Download_BOMTime", cpe_get_igd_Download_BOMTime},
    {"cpe_get_igd_Download_EOMTime", cpe_get_igd_Download_EOMTime},
    {"cpe_get_igd_Download_TestBytesReceived", cpe_get_igd_Download_TestBytesReceived},
    {"cpe_get_igd_Download_TotalBytesReceived", cpe_get_igd_Download_TotalBytesReceived},
    {"cpe_get_igd_Download_TCPOpenRequestTime", cpe_get_igd_Download_TCPOpenRequestTime},
    {"cpe_get_igd_Download_TCPOpenResponseTime", cpe_get_igd_Download_TCPOpenResponseTime},

    {"cpe_get_igd_Upload_DiagnosticsState", cpe_get_igd_Upload_DiagnosticsState},
    {"cpe_set_igd_Upload_DiagnosticsState", cpe_set_igd_Upload_DiagnosticsState},
    {"cpe_get_igd_Upload_Interface", cpe_get_igd_Upload_Interface},
    {"cpe_set_igd_Upload_Interface", cpe_set_igd_Upload_Interface},
    {"cpe_get_igd_Upload_URL", cpe_get_igd_Upload_URL},
    {"cpe_set_igd_Upload_URL", cpe_set_igd_Upload_URL},
    {"cpe_get_igd_Upload_DSCP", cpe_get_igd_Upload_DSCP},
    {"cpe_set_igd_Upload_DSCP", cpe_set_igd_Upload_DSCP},
    {"cpe_get_igd_Upload_EthernetPriority", cpe_get_igd_Upload_EthernetPriority},
    {"cpe_set_igd_Upload_EthernetPriority", cpe_set_igd_Upload_EthernetPriority},
    {"cpe_get_igd_Upload_TestFileLength", cpe_get_igd_Upload_TestFileLength},
    {"cpe_set_igd_Upload_TestFileLength", cpe_set_igd_Upload_TestFileLength},
    {"cpe_get_igd_Upload_ROMTime", cpe_get_igd_Upload_ROMTime},
    {"cpe_get_igd_Upload_BOMTime", cpe_get_igd_Upload_BOMTime},
    {"cpe_get_igd_Upload_EOMTime", cpe_get_igd_Upload_EOMTime},
    {"cpe_get_igd_Upload_TotalBytesSent", cpe_get_igd_Upload_TotalBytesSent},
    {"cpe_get_igd_Upload_TCPOpenRequestTime", cpe_get_igd_Upload_TCPOpenRequestTime},
    {"cpe_get_igd_Upload_TCPOpenResponseTime", cpe_get_igd_Upload_TCPOpenResponseTime},

	{"cpe_get_igd_UdpEcho_Enable", cpe_get_igd_UdpEcho_Enable},
	{"cpe_set_igd_UdpEcho_Enable", cpe_set_igd_UdpEcho_Enable},
	{"cpe_get_igd_UdpEcho_Interface", cpe_get_igd_UdpEcho_Interface},
	{"cpe_set_igd_UdpEcho_Interface", cpe_set_igd_UdpEcho_Interface},
	{"cpe_get_igd_UdpEcho_SourceIPAddress", cpe_get_igd_UdpEcho_SourceIPAddress},
	{"cpe_set_igd_UdpEcho_SourceIPAddress", cpe_set_igd_UdpEcho_SourceIPAddress},
	{"cpe_get_igd_UdpEcho_UDPPort", cpe_get_igd_UdpEcho_UDPPort},
	{"cpe_set_igd_UdpEcho_UDPPort", cpe_set_igd_UdpEcho_UDPPort},
	{"cpe_get_igd_UdpEcho_EchoPlusEnabled", cpe_get_igd_UdpEcho_EchoPlusEnabled},
	{"cpe_set_igd_UdpEcho_EchoPlusEnabled", cpe_set_igd_UdpEcho_EchoPlusEnabled},
	{"cpe_get_igd_UdpEcho_EchoPlusSupported", cpe_get_igd_UdpEcho_EchoPlusSupported},
	{"cpe_get_igd_UdpEcho_PacketsReceived", cpe_get_igd_UdpEcho_PacketsReceived},
	{"cpe_get_igd_UdpEcho_PacketsResponded", cpe_get_igd_UdpEcho_PacketsResponded},
	{"cpe_get_igd_UdpEcho_BytesReceived", cpe_get_igd_UdpEcho_BytesReceived},
	{"cpe_get_igd_UdpEcho_BytesResponded", cpe_get_igd_UdpEcho_BytesResponded},
	{"cpe_get_igd_UdpEcho_TimeFirstPacketReceived", cpe_get_igd_UdpEcho_TimeFirstPacketReceived},
	{"cpe_get_igd_UdpEcho_TimeLastPacketReceived", cpe_get_igd_UdpEcho_TimeLastPacketReceived},

	{"cpe_get_igd_di_X_CMCC_Monitor_Enable", cpe_get_igd_di_X_CMCC_Monitor_Enable},
    {"cpe_set_igd_di_X_CMCC_Monitor_Enable", cpe_set_igd_di_X_CMCC_Monitor_Enable},

    {"cpe_get_igd_di_X_CMCC_Monitor_MonitorNumberOfEntries", cpe_get_igd_di_X_CMCC_Monitor_MonitorNumberOfEntries},

    {"cpe_add_igd_X_CMCC_MonitorConfig", cpe_add_igd_X_CMCC_MonitorConfig},
    {"cpe_del_igd_X_CMCC_MonitorConfig", cpe_del_igd_X_CMCC_MonitorConfig},

    {"cpe_get_igd_di_X_CMCC_Monitor_ParaList", cpe_get_igd_di_X_CMCC_Monitor_ParaList},
    {"cpe_set_igd_di_X_CMCC_Monitor_ParaList", cpe_set_igd_di_X_CMCC_Monitor_ParaList},

    {"cpe_get_igd_di_X_CMCC_Monitor_TimeList", cpe_get_igd_di_X_CMCC_Monitor_TimeList},
    {"cpe_set_igd_di_X_CMCC_Monitor_TimeList", cpe_set_igd_di_X_CMCC_Monitor_TimeList},
    
    {"cpe_refresh_igd_ddnsconnection", cpe_refresh_igd_ddnsconnection},
    {"cpe_get_igd_ddns_Value_DDNSCfgEnabled", cpe_get_igd_ddns_Value_DDNSCfgEnabled},
    {"cpe_get_igd_ddns_Value_DDNSProvider", cpe_get_igd_ddns_Value_DDNSProvider},
    {"cpe_get_igd_ddns_Value_DDNSUsername", cpe_get_igd_ddns_Value_DDNSUsername},
    {"cpe_get_igd_ddns_Value_DDNSPassword", cpe_get_igd_ddns_Value_DDNSPassword},
    {"cpe_get_igd_ddns_Value_ServicePort", cpe_get_igd_ddns_Value_ServicePort},
    {"cpe_get_igd_ddns_Value_DDNSDomainName", cpe_get_igd_ddns_Value_DDNSDomainName},
    {"cpe_get_igd_ddns_Value_DDNSHostName", cpe_get_igd_ddns_Value_DDNSHostName},
    {"cpe_set_igd_ddns_Value_DDNSCfgEnabled", cpe_set_igd_ddns_Value_DDNSCfgEnabled},
    {"cpe_set_igd_ddns_Value_DDNSProvider", cpe_set_igd_ddns_Value_DDNSProvider},
    {"cpe_set_igd_ddns_Value_DDNSUsername", cpe_set_igd_ddns_Value_DDNSUsername},
    {"cpe_set_igd_ddns_Value_DDNSPassword", cpe_set_igd_ddns_Value_DDNSPassword},
    {"cpe_set_igd_ddns_Value_ServicePort", cpe_set_igd_ddns_Value_ServicePort},
    {"cpe_set_igd_ddns_Value_DDNSDomainName", cpe_set_igd_ddns_Value_DDNSDomainName},
    {"cpe_set_igd_ddns_Value_DDNSHostName", cpe_set_igd_ddns_Value_DDNSHostName},


	{"cpe_add_igd_wandevice", cpe_add_igd_wandevice},
	{"cpe_add_igd_WANIPConnection", cpe_add_igd_WANIPConnection},
	{"cpe_add_igd_WANConnectionDevice", cpe_add_igd_WANConnectionDevice},
	{"cpe_get_igd_WANConnectionNumberOfEntries", cpe_get_igd_WANConnectionNumberOfEntries},
	{"cpe_set_igd_WANConnectionNumberOfEntries", cpe_set_igd_WANConnectionNumberOfEntries},

	{"cpe_setattr_igd_ms_connectionrequesturl", cpe_setattr_igd_ms_connectionrequesturl},

    {"cpe_refresh_igd_LANDevice", cpe_refresh_igd_LANDevice},
    {"cpe_refresh_igd_IPInterface", cpe_refresh_igd_IPInterface},
    {"cpe_refresh_igd_LANEthernetInterfaceConfig", cpe_refresh_igd_LANEthernetInterfaceConfig},
    {"cpe_refresh_igd_WLANConfiguration", cpe_refresh_igd_WLANConfiguration},
    {"cpe_refresh_igd_AssociatedDevice", cpe_refresh_igd_AssociatedDevice},
    {"cpe_get_igd_EnableOfWLAN", cpe_get_igd_EnableOfWLAN},
    {"cpe_set_igd_EnableOfWLAN", cpe_set_igd_EnableOfWLAN},
    {"cpe_get_igd_StatusOfWLAN", cpe_get_igd_StatusOfWLAN},
    {"cpe_get_igd_NameOfWLANConfiguration", cpe_get_igd_NameOfWLANConfiguration},
    {"cpe_get_igd_BSSID", cpe_get_igd_BSSID},
    {"cpe_get_FirstUseDate", cpe_get_FirstUseDate},
    {"cpe_get_ProcessorNumberOfEntries", cpe_get_ProcessorNumberOfEntries},

    {"cpe_get_TotalOfMemoryStatus", cpe_get_TotalOfMemoryStatus},
    {"cpe_get_FreeOfMemoryStatus", cpe_get_FreeOfMemoryStatus},
    {"cpe_get_CPUUsage", cpe_get_CPUUsage},
    {"cpe_get_ProcessNumberOfEntries", cpe_get_ProcessNumberOfEntries},
    {"cpe_refresh_ProcessStatus", cpe_refresh_ProcessStatus},
    {"cpe_get_PIDOfProcess", cpe_get_PIDOfProcess},
    {"cpe_get_CommandOfProcess", cpe_get_CommandOfProcess},
    {"cpe_get_SizeOfProcess", cpe_get_SizeOfProcess},
    {"cpe_get_StateOfProcess", cpe_get_StateOfProcess},
    {"cpe_refresh_Processor", cpe_refresh_Processor},
    {"cpe_get_ArchitectureOfProcessor", cpe_get_ArchitectureOfProcessor},
    {"cpe_refresh_VendorLogFile", cpe_refresh_VendorLogFile},
    {"cpe_get_NameOfVendorLogFile", cpe_get_NameOfVendorLogFile},
    {"cpe_get_MaximumSizeOfVendorLogFile", cpe_get_MaximumSizeOfVendorLogFile},
    {"cpe_get_PersistentOfVendorLogFile", cpe_get_PersistentOfVendorLogFile},
    {"cpe_get_EnableCWMP", cpe_get_EnableCWMP},
    {"cpe_get_igd_NameOfWLANConfiguration", cpe_get_igd_NameOfWLANConfiguration},
    {"cpe_get_igd_MaxBitRateOfWlan", cpe_get_igd_MaxBitRateOfWlan},
    {"cpe_get_igd_Channel", cpe_get_igd_Channel},
    {"cpe_set_igd_Channel", cpe_set_igd_Channel},
    {"cpe_get_igd_AutoChannelEnable", cpe_get_igd_AutoChannelEnable},
    {"cpe_set_idg_AutoChannelEnable", cpe_set_idg_AutoChannelEnable},
    {"cpe_get_igd_SSID", cpe_get_igd_SSID},
    {"cpe_set_igd_SSID", cpe_set_igd_SSID},
    {"cpe_get_igd_BeaconType", cpe_get_igd_BeaconType},
    {"cpe_set_igd_BeaconType", cpe_set_igd_BeaconType},
    {"cpe_get_igd_MACAddressControlEnabled", cpe_get_igd_MACAddressControlEnabled},
    {"cpe_get_igd_Standard", cpe_get_igd_Standard},
    {"cpe_set_igd_Standard", cpe_set_igd_Standard},
    {"cpe_get_igd_WEPKeyIndex", cpe_get_igd_WEPKeyIndex},
    {"cpe_set_igd_WEPKeyIndex", cpe_set_igd_WEPKeyIndex},
    {"cpe_get_igd_WEPEncryptionLevel", cpe_get_igd_WEPEncryptionLevel},
    {"cpe_get_igd_BasicEncryptionModes", cpe_get_igd_BasicEncryptionModes},
    {"cpe_get_igd_BasicAuthenticationMode", cpe_get_igd_BasicAuthenticationMode},
    {"cpe_get_igd_WPAEncryptionModes", cpe_get_igd_WPAEncryptionModes},
    {"cpe_set_igd_WPAEncryptionModes", cpe_set_igd_WPAEncryptionModes},
    {"cpe_get_igd_WPAAuthenticationMode", cpe_get_igd_WPAAuthenticationMode},
    {"cpe_set_igd_WPAAuthenticationMode", cpe_set_igd_WPAAuthenticationMode},
    {"cpe_get_igd_IEEE11iEncryptionModes", cpe_get_igd_IEEE11iEncryptionModes},
    {"cpe_get_igd_IEEE11iAuthenticationMode", cpe_get_igd_IEEE11iAuthenticationMode},
    {"cpe_get_igd_PossibleChannels", cpe_get_igd_PossibleChannels},
    {"cpe_get_igd_BasicDataTransmitRates", cpe_get_igd_BasicDataTransmitRates},
    {"cpe_get_igd_OperationalDataTransmitRates", cpe_get_igd_OperationalDataTransmitRates},
    {"cpe_get_igd_PossibleDataTransmitRates", cpe_get_igd_PossibleDataTransmitRates},
    {"cpe_get_InsecureOOBAccessEnabled", cpe_get_InsecureOOBAccessEnabled},
    {"cpe_get_BeaconAdvertisementEnabled", cpe_get_BeaconAdvertisementEnabled},
    {"cpe_get_igd_SSIDAdvertisementEnabled", cpe_get_igd_SSIDAdvertisementEnabled},
    {"cpe_set_igd_SSIDAdvertisementEnabled", cpe_set_igd_SSIDAdvertisementEnabled},
    {"cpe_get_igd_RadioEnabled", cpe_get_igd_RadioEnabled},
    {"cpe_get_TransmitPowerSupported", cpe_get_TransmitPowerSupported},
    {"cpe_get_TransmitPower", cpe_get_TransmitPower},
    {"cpe_set_TransmitPower", cpe_set_TransmitPower},
    {"cpe_get_igd_AutoRateFallBackEnabled", cpe_get_igd_AutoRateFallBackEnabled},
    {"cpe_get_ChannelsInUse", cpe_get_ChannelsInUse},
    {"cpe_get_DeviceOperationMode", cpe_get_DeviceOperationMode},
    {"cpe_get_AuthenticationServiceMode", cpe_get_AuthenticationServiceMode},
    {"cpe_get_WMMSupported", cpe_get_WMMSupported},
    {"cpe_get_UAPSDSupported", cpe_get_UAPSDSupported},
    {"cpe_get_igd_WMMEnable", cpe_get_igd_WMMEnable},
    {"cpe_set_igd_WMMEnable", cpe_set_igd_WMMEnable},
    {"cpe_get_igd_UAPSDEnable", cpe_get_igd_UAPSDEnable},
    {"cpe_get_igd_TotalBytesSent", cpe_get_igd_TotalBytesSent},
    {"cpe_get_igd_TotalBytesReceived", cpe_get_igd_TotalBytesReceived},
    {"cpe_get_igd_TotalPacketsSent", cpe_get_igd_TotalPacketsSent},
    {"cpe_get_igd_TotalPacketsReceived", cpe_get_igd_TotalPacketsReceived},
    {"cpe_get_igd_TotalAssociations", cpe_get_igd_TotalAssociations},
    {"cpe_get_igd_ErrorsReceived", cpe_get_igd_ErrorsReceived},
    {"cpe_get_igd_ErrorsSent", cpe_get_igd_ErrorsSent},
    {"cpe_get_DiscardPacketsSentOfWlan", cpe_get_DiscardPacketsSentOfWlan},
    {"cpe_get_DiscardPacketsReceivedOfWlan", cpe_get_DiscardPacketsReceivedOfWlan},
    {"cpe_get_EnableOfWPS", cpe_get_EnableOfWPS},
    {"cpe_set_EnableOfWPS", cpe_set_EnableOfWPS},
    {"cpe_get_DeviceName", cpe_get_DeviceName},
    {"cpe_get_DevicePassword", cpe_get_DevicePassword},
    {"cpe_set_DevicePassword", cpe_set_DevicePassword},
    {"cpe_get_VersionOfWPS", cpe_get_VersionOfWPS},
    {"cpe_get_ConfigMethodsSupported", cpe_get_ConfigMethodsSupported},
    {"cpe_get_ConfigMethodsEnabled", cpe_get_ConfigMethodsEnabled},
    {"cpe_set_ConfigMethodsEnabled", cpe_set_ConfigMethodsEnabled},
    {"cpe_get_SetupLockedState", cpe_get_SetupLockedState},
    {"cpe_get_ConfigurationState", cpe_get_ConfigurationState},
    {"cpe_get_LastConfigurationError", cpe_get_LastConfigurationError},
    {"cpe_get_RegistrarNumberOfEntries", cpe_get_RegistrarNumberOfEntries},
    {"cpe_get_RegistrarEstablishedOfWPS", cpe_get_RegistrarEstablishedOfWPS},
    {"cpe_get_WPSRegistrarEnable", cpe_get_WPSRegistrarEnable},
    {"cpe_set_WPSRegistrarEnable", cpe_set_WPSRegistrarEnable},
    {"cpe_get_WPSRegistrarUUID", cpe_get_WPSRegistrarUUID},
    {"cpe_get_WPSRegistrarDeviceName", cpe_get_WPSRegistrarDeviceName},
    {"cpe_refresh_igd_WPSRegistrar", cpe_refresh_igd_WPSRegistrar},
    {"cpe_refresh_igd_AssociatedDevice", cpe_refresh_igd_AssociatedDevice},
    {"cpe_get_AssociatedDeviceMACAddress", cpe_get_AssociatedDeviceMACAddress},
    {"cpe_get_AssociatedDeviceIPAddress", cpe_get_AssociatedDeviceIPAddress},
    {"cpe_get_AssociatedDeviceAuthenticationState", cpe_get_AssociatedDeviceAuthenticationState},
    {"cpe_get_LastDataTransmitRate", cpe_get_LastDataTransmitRate},
    {"cpe_refresh_igd_WEPKey", cpe_refresh_igd_WEPKey},
    {"cpe_refresh_igd_PreSharedKey", cpe_refresh_igd_PreSharedKey},
    {"cpe_get_igd_WEPKey", cpe_get_igd_WEPKey},
    {"cpe_set_igd_WEPKey", cpe_set_igd_WEPKey},
    {"cpe_get_igd_LANEthernetInterfaceNumberOfEntries", cpe_get_igd_LANEthernetInterfaceNumberOfEntries},
    {"cpe_get_igd_LANWLANConfigurationNumberOfEntries", cpe_get_igd_LANWLANConfigurationNumberOfEntries},
    {"cpe_get_PersistentData", cpe_get_PersistentData},
    {"cpe_get_ConfigFile", cpe_get_ConfigFile},
   // {"cpe_set_ConfigFile", cpe_set_ConfigFile},
    {"cpe_get_SupportedConnReqMethods", cpe_get_SupportedConnReqMethods},
    {"cpe_get_EnableOfRemoteAccess", cpe_get_EnableOfRemoteAccess},
    {"cpe_set_EnableOfRemoteAccess", cpe_set_EnableOfRemoteAccess},
    {"cpe_get_SupportedProtocolsOfRemoteAccess", cpe_get_SupportedProtocolsOfRemoteAccess},
    {"cpe_get_ProtocolOfRemoteAccess", cpe_get_ProtocolOfRemoteAccess},
    {"cpe_get_RadioNumberOfEntries", cpe_get_RadioNumberOfEntries},
    {"cpe_get_SSIDNumberOfEntries", cpe_get_SSIDNumberOfEntries},
    {"cpe_get_AccessPointNumberOfEntries", cpe_get_AccessPointNumberOfEntries},
    {"cpe_get_EndPointNumberOfEntries", cpe_get_EndPointNumberOfEntries},
    {"cpe_refresh_RadioOfDevice", cpe_refresh_RadioOfDevice},
    {"cpe_get_StatusOfRadio", cpe_get_StatusOfRadio},
    {"cpe_get_SupportedFrequencyBands", cpe_get_SupportedFrequencyBands},
    {"cpe_get_SupportedStandardsOfRadio", cpe_get_SupportedStandardsOfRadio},
    {"cpe_get_AutoChannelSupportedOfRadio", cpe_get_AutoChannelSupportedOfRadio},
    {"cpe_get_AutoChannelRefreshPeriod", cpe_get_AutoChannelRefreshPeriod},
    {"cpe_get_OperatingChannelBandwidth", cpe_get_OperatingChannelBandwidth},
    {"cpe_get_CurrentOperatingChannelBandwidth", cpe_get_CurrentOperatingChannelBandwidth},
    {"cpe_get_AboveControlChannel", cpe_get_AboveControlChannel},
    {"cpe_get_GuardInterval", cpe_get_GuardInterval},
    {"cpe_get_MCSOfRadio", cpe_get_MCSOfRadio},
    {"cpe_get_IEEE80211hSupported", cpe_get_IEEE80211hSupported},
    {"cpe_get_IEEE80211hEnabled", cpe_get_IEEE80211hEnabled},
    {"cpe_refresh_SSIDOfDevice", cpe_refresh_SSIDOfDevice},
    {"cpe_refresh_AccessPointOfDevice", cpe_refresh_AccessPointOfDevice},
    
    {"cpe_refresh_X_TOZED_APN_PROFILE", cpe_refresh_X_TOZED_APN_PROFILE},
    {"cpe_get_CurrentProfileOfAPN", cpe_get_CurrentProfileOfAPN},
    {"cpe_set_CurrentProfileOfAPN", cpe_set_CurrentProfileOfAPN},
    {"cpe_get_ProfileNameOfAPN", cpe_get_ProfileNameOfAPN},
    {"cpe_set_ProfileNameOfAPN", cpe_set_ProfileNameOfAPN},
    {"cpe_get_APNNameOfAPN", cpe_get_APNNameOfAPN},
    {"cpe_set_APNNameOfAPN", cpe_set_APNNameOfAPN},
    {"cpe_get_PPPUserNameOfAPN", cpe_get_PPPUserNameOfAPN},
    {"cpe_set_PPPUserNameOfAPN", cpe_set_PPPUserNameOfAPN},
    {"cpe_get_PPPPasswdOfAPN", cpe_get_PPPPasswdOfAPN},
    {"cpe_set_PPPPasswdOfAPN", cpe_set_PPPPasswdOfAPN},
    {"cpe_get_AuthTypeOfAPN", cpe_get_AuthTypeOfAPN},
    {"cpe_set_AuthTypeOfAPN", cpe_set_AuthTypeOfAPN},

    {"cpe_get_WANAccessType", cpe_get_WANAccessType},
    {"cpe_refresh_ConnectionOfWANCommonInterface", cpe_refresh_ConnectionOfWANCommonInterface},
    {"cpe_get_ActiveConnectionDeviceContainer", cpe_get_ActiveConnectionDeviceContainer},
    {"cpe_get_ActiveConnectionServiceID", cpe_get_ActiveConnectionServiceID},
    {"cpe_get_NetworkPriority", cpe_get_NetworkPriority},
    {"cpe_set_NetworkPriority", cpe_set_NetworkPriority},
    {"cpe_get_UplinkRate", cpe_get_UplinkRate},
    {"cpe_get_DownlinkRate", cpe_get_DownlinkRate},
    {"cpe_get_Duration", cpe_get_Duration},
    {"cpe_get_USIMCardStatus", cpe_get_USIMCardStatus},
    {"cpe_get_IPv4Status", cpe_get_IPv4Status},
    {"cpe_set_IPv4Status", cpe_set_IPv4Status},
    {"cpe_get_IPv6Status", cpe_get_IPv6Status},
    {"cpe_set_IPv6Status", cpe_set_IPv6Status},
    
    {"cpe_get_MaxUplinkRate", cpe_get_MaxUplinkRate},
    {"cpe_get_MaxDownlinkRate", cpe_get_MaxDownlinkRate},
    {"cpe_get_CommonStatus_BitErrorRate", cpe_get_CommonStatus_BitErrorRate},
    {"cpe_get_CommonStatus_Resync", cpe_get_CommonStatus_Resync},

};

int get_index_after_paramname(parameter_node_t * param, const char * tag_name)
{
    parameter_node_t * parent;
    parameter_node_t * tmp;
    for(parent=param->parent, tmp = param; parent; tmp = parent, parent = parent->parent)
    {
        if(TRstrcmp(parent->name, tag_name) == 0)
        {
             if(is_digit(tmp->name) == 0)
             {
                return TRatoi(tmp->name);   
             }
        }        
    }
    return -1;
}


void cwmp_model_load(cwmp_t * cwmp, const char * xmlfile)
{  

    cwmp_model_load_xml(cwmp, xmlfile, ModelFunction, sizeof(ModelFunction)/sizeof(model_func_t));
}


