#!/bin/sh
#
#fengyz @ tz 
#the handler script for wlan button
[ "${ACTION}" = "released" ] || exit 0

logger "$BUTTON pressed for $SEEN seconds"


if [ "$SEEN" -lt 1 ]
then
    for var in `uci show wireless | grep ifname | cut -d'=' -f 1`
    do
        ifname=`uci get $var`
        res=`iwconfig $ifname | grep ESSID | wc -l`
        if [[ $res == "1" ]];then
	        echo "Stop wifi... " > /dev/console
            /sbin/wifi down

        else
	        echo "Start wifi... " > /dev/console
            /sbin/wifi 
        fi
        return 0
    done



elif [ "$SEEN" -gt 5 ]
then
    echo "pressed 5 sec"
fi

return 0
