#!/bin/sh
#
#fengyz @ tz 
if [ -e /tmp/.in_peripheral_test ]; then
	touch /tmp/.wps_button_press
fi

[ "${ACTION}" = "released" ] || exit 0

logger "$BUTTON pressed for $SEEN seconds"

if [ -e /tmp/.in_peripheral_test ]; then
	rm /tmp/.wps_button_press
	exit
fi

/sbin/wps_handler

echo "wps key pressed " > /dev/console

return 0
