#!/usr/bin/lua
function usage()
print([[usage: getinfacestatus <-i inf> [-p param] 
       -i  inf    interface name 
       -p  param  interface param 
eoxamples:
       getinfacestatus -i wan -p ipv4-address'
       ]])
end

function arg_parse(arg)
local res=nil
local i=1

if 4 > #arg then
    usage()
end

while i <= #arg do
    if "-i" == arg[i] and arg[i+1] and "-" ~= string.sub(arg[i+1],1,1) then
       if not res then res = {} end
       res["inf"] = arg[i+1]
       i = i + 1
    elseif "-p" == arg[i] and arg[i+1] and "-" ~= string.sub(arg[i+1],1,1) then
       if not res then res = {} end
       res["param"] = arg[i+1]
       i = i + 1
    end
    i = i + 1
end
return res
end

function utilexec(command)                                                   
        local pp   = io.popen(command)
        local data = pp:read("*a")
        pp:close()
  
        return data                    
end


--main--
local arg_t = arg_parse(arg)
if arg_t and arg_t["inf"] and arg_t["param"] then 
    local ifa = utilexec("ubus call " .. string.format("network.interface.%s",arg_t["inf"]) .. " status")
    if ifa then
        ifa = string.gsub(ifa,",","")
        local p = arg_t["param"]
        if "ipv4-address" == p then
            local cmd =  "echo \"" .. ifa .. "\"|grep \"address\"|awk '{print $2}'|sed -n '3p'"                    
            os.execute(cmd) 
        elseif "l3_device" == p then                                                                     
            local cmd =  "echo \"" .. ifa .. "\"|grep \"l3_device\"|awk '{print $2}'"                    
            os.execute(cmd) 
        elseif "dns-server" == p then
            local cmd =  "echo \"" .. ifa .. "\"|grep \"address\"|awk '{print $2}'|sed -n '3p'"                    
            os.execute(cmd) 
        elseif "nexthop" == p then
            local cmd =  "echo \"" .. ifa .. "\"|grep \"nexthop\"|awk '{print $2}'|sed -n '2p'"                    
            os.execute(cmd) 
        elseif "mac" == p then
            local cmd = string.format([[ifconfig %s | grep HWaddr | awk '{print $5}']],"eth0.2")
            os.execute(cmd)
        elseif "netmask" == p then
            local cmd = string.format([[ifconfig %s | grep Mask | awk -F: '{print $4}']],"eth0.2")
            os.execute(cmd)
        else
            if ifa[p] and "table" ~= type(ifa[p]) then
                print(ifa[p])
            end
        end 
    end
end

