#!/bin/sh

FORM_CONFIG_STATION=/tmp/form_config/
FACTORY_CONFIG_FILE=/etc/tozed_param
WEB_CONFIG_LOAD_FILE=${FORM_CONFIG_STATION}/web

mkdir -p ${FORM_CONFIG_STATION}

#export param
cat ${FACTORY_CONFIG_FILE} | grep TZWEB_ > ${WEB_CONFIG_LOAD_FILE}
chmod 777 ${WEB_CONFIG_LOAD_FILE}
. ${WEB_CONFIG_LOAD_FILE}



if [ "${TZWEB_SHOW_LANGUAGE_SELECT}" = "0" ]; then
	cfg -a TZ_WEB_SHOW_LANGUAGE_SELECT="0" --section web
else
	cfg -a TZ_WEB_SHOW_LANGUAGE_SELECT="1" --section web
fi

if [ "${TZWEB_PREFERRED_LANGUAGE}" = "" ]; then
	cfg -a TZ_WEB_LANGUAGE="en" --section web
	/etc/tool_script/set_web_language en
else
	cfg -a TZ_WEB_LANGUAGE="${TZWEB_PREFERRED_LANGUAGE}" --section web
	/etc/tool_script/set_web_language ${TZWEB_PREFERRED_LANGUAGE}
fi

if [ "${TZWEB_USER_SHOW_HIDE_PREF}" != "" ]; then
	cfg -a TZ_WEB_USER_SHOW_HIDE_PREF="${TZWEB_USER_SHOW_HIDE_PREF}" --section web
else
	cfg -a TZ_WEB_USER_SHOW_HIDE_PREF="BF" --section web
fi

if [ "${TZWEB_OPERATOR_SHOW_HIDE_PREF}" != "" ]; then
	cfg -a TZ_WEB_OPERATOR_SHOW_HIDE_PREF="${TZWEB_OPERATOR_SHOW_HIDE_PREF}" --section web
else
	cfg -a TZ_WEB_OPERATOR_SHOW_HIDE_PREF="FFFF" --section web
fi

if [ "${TZWEB_SESSION_TIMEOUT}" != "" ]; then
	cfg -a TZ_SESSION_TIMEOUT="${TZWEB_SESSION_TIMEOUT}" --section web
else
	cfg -a TZ_SESSION_TIMEOUT="20" --section web
fi

if [ "${TZWEB_HTTPS_PORT}" != "" ]; then
	cfg -a TZ_HTTPS_PORT="${TZWEB_HTTPS_PORT}" --section web
else
	cfg -a TZ_HTTPS_PORT="8888" --section web
fi

cfg -c

