#!/bin/sh
#sztozed shenzhen fengyz
#openwrt wps pbc  for mt7603e mt7612e

. /lib/functions.sh
inter_sections=""

config_cb() {
        local type="$1"
        local section="$2"

        case "$type" in
                wifi-iface)
                        append inter_sections "$section"
                ;;
        esac
}
config_load "${cfgfile:-wireless}"

check_device_connect() {

    echo timer > /sys/class/leds/blue:wps/trigger

    if [ $3'' == '2.4G' ];then
        echo 200 > /sys/class/leds/blue:wps/delay_on 
        echo 100 > /sys/class/leds/blue:wps/delay_off
    else
        echo 500 > /sys/class/leds/blue:wps/delay_on 
        echo 100 > /sys/class/leds/blue:wps/delay_off
    fi
	
    local count=120
    local on_cli=0
    while [ $count -gt 0 -a $on_cli -le $1 ]
	do
		let count=$count-1
		on_cli=`iwpriv $2 get_on_cli | grep -v $2 | grep -v MAC| grep -v ^$ | wc -l`
		sleep 1
	done

    iwpriv $2 set WscStop=1
	echo none > /sys/class/leds/blue:wps/trigger
	echo 0 > /sys/class/leds/blue:wps/brightness
}


for section in $inter_sections
do
        config_get wps $section wps
        config_get ifname $section ifname
        config_get device $section device
        config_get band $device band

        if [ $1'' != $band'' ];then
            continue
        fi

        if [ $ifname'' == "" ];then
            continue;
        fi


        if [ $wps'' == 'pbc' ];then
		   local cur_cli=`iwpriv $ifname get_on_cli | grep -v $ifname | grep -v MAC | grep -v ^$ | wc -l`
           iwpriv $ifname set WscStop=1
           iwpriv $ifname set WscConfMode=7
           iwpriv $ifname set WscMode=2
           iwpriv $ifname set WscGetConf=1
           check_device_connect  $cur_cli  $ifname $band
        fi

done
