#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	uci commit
}

boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	mkdir -p /tmp/.jail
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	/sbin/kmodloader

	# allow wifi modules time to settle
	sleep 1
	touch /tmp/darren.txt

	#2.4g wifi
	/etc/tozed/tz_form_wifi

	if [ -f /etc/.flag_factory_config ]; then
		cp /rom/etc/config/tozed /etc/config/tozed
		/etc/tozed/tz_form_tozed_modem
		/etc/tozed/tz_form_tozed_remote
		/etc/tozed/tz_form_tozed_web
		/etc/tozed/tz_form_tozed_system
		tozed_tool -c config -g WEB_USER -w rewrite
	fi

	#/etc/config/network
	/bin/board_detect

	if [ -f /etc/.flag_factory_config ]; then
		/etc/tozed/tz_form_network
	fi

	#/etc/config/dhcp
	if [ -f /etc/.flag_factory_config ]; then
		/etc/tozed/tz_form_dhcp
	fi

	#/etc/config/tozed tr069
	if [ -f /etc/.flag_factory_config ]; then
		/etc/tozed/tz_form_tozed_tr069
	fi

	uci_apply_defaults
	
	rm -rf /etc/.flag_factory_config


	if [ -e /etc/config_update_file/updateconfig.conf ]; then
		/etc/tozed/tz_config_append /etc/config_update_file/updateconfig.conf
		rm /etc/config_update_file/updateconfig.conf
	fi

	#/etc/tozed/tz_test/time_to_capture_message.sh &

	# temporary hack until configd exists
	/sbin/reload_config

	#/etc/tozed/tz_test/soft_reboot_test.sh	& 

	# create /dev/root if it doesn't exist
	[ -e /dev/root -o -h /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}
}
